### ISSUE TITLE
Error when running container

### ISSUE THREAD

**Issue by andrewm659** [RezaImany/Veeam-Enterprise-Manager-Prometheus-Exporter#1]
```
sudo docker logs 091a527c301e
Traceback (most recent call last):
  File "/python/veeamEnterpriseManager_exporter.py", line 40, in <module>
    sessionEncodedBytes= base64.b64encode(veeamSessionId.encode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by RezaImany** [comment]
hi drew
i checked it and it works very well
have you entered your server ip and port and your credential in the .py file??

i will produce a docker-compose file with environment variable support for ease of use

**Comment by RezaImany** [comment]
i just updated the repo
clone it again and update docker-compose file and use it
@andrewm659

**Comment by andrewm659** [comment]
Updated the repo on my server created the container image.  Now I get that this:

```
 ~]$ sudo docker run -p 8000:8000 --name veeamentmgr_exporter ff3bdf353bef
Traceback (most recent call last):
  File "/python/veeamEnterpriseManager_exporter.py", line 20, in <module>
    veeambase= (veeamUsername + ":" +veeamPassword)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by RezaImany** [comment]
i just updated the repo

just clone and update docker-compose file and use this command in repo

docker-compose up -d
